name: crystal_growth_assistant
description: A mobile app for crystal growth experiment recording

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  http: ^1.2.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path: ^1.8.3
  path_provider: ^2.1.3
  
  # UI dependencies
  flutter_markdown: ^0.6.19
  image_picker: ^1.1.1
  fluttertoast: ^8.2.5
  permission_handler: ^11.3.1
  
  # State management
  provider: ^6.1.2

  # For webview (if needed)
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/